version: '3.8'

services:
  jobmanager:
    build: ./sql-client
    command: jobmanager
    ports:
      - "8081:8081"
    volumes:
      - flink_data:/tmp/
      - ./jaas.conf:/opt/flink/conf/jaas.conf
    environment:
      FLINK_PROPERTIES: |-
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
        kafka.bootstrap.servers: <your-bootstrap-server>
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        java.security.auth.login.config: /opt/flink/conf/jaas.conf
      JAVA_TOOL_OPTIONS: -Djava.security.auth.login.config=/opt/flink/conf/jaas.conf
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

  taskmanager:
    build: ./sql-client
    command: taskmanager
    depends_on:
      - jobmanager
    volumes:
      - flink_data:/tmp/
      - ./jaas.conf:/opt/flink/conf/jaas.conf
    environment:
      FLINK_PROPERTIES: |-
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        web.backpressure.refresh-interval: 10000
        kafka.bootstrap.servers: <your-bootstrap-server>
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        java.security.auth.login.config: /opt/flink/conf/jaas.conf
        taskmanager.numberOfTaskSlots: 4
      JAVA_TOOL_OPTIONS: -Djava.security.auth.login.config=/opt/flink/conf/jaas.conf
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

  sql-client:
    build: ./sql-client
    command: bash -c "while true; do sleep 1000; done"
    depends_on:
      - jobmanager
    volumes:
      - ./jaas.conf:/opt/flink/conf/jaas.conf
    environment:
      FLINK_PROPERTIES: |-
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
        kafka.bootstrap.servers: <your-bootstrap-server>
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        java.security.auth.login.config: /opt/flink/conf/jaas.conf
      JAVA_TOOL_OPTIONS: -Djava.security.auth.login.config=/opt/flink/conf/jaas.conf

volumes:
  flink_data:
